"""
AI Document Assistant
======================
A Streamlit app that lets you upload documents (PDF, DOCX, TXT, MD) or pull them
from Google Drive, then ask questions about them. Answers are generated by Groq
using a hybrid (semantic + keyword) search over your documents, with sources shown.

The file is organized into clearly labeled sections so it's easy to follow:
  1. Setup & config
  2. Document extraction  (per file type)
  3. Text chunking
  4. Embeddings (Sentence Transformers) + FAISS index
  5. Keyword search
  6. Hybrid search
  7. Groq question answering
  8. Google Drive loading
  9. Streamlit UI (ties everything together, with caching via session_state)
"""

import os
import re
import tempfile

import numpy as np
import streamlit as st

# ----------------------------------------------------------------------------
# 1. SETUP & CONFIG
# ----------------------------------------------------------------------------

st.set_page_config(page_title="AI Document Assistant", layout="wide")

CHUNK_SIZE = 800        # characters per chunk
CHUNK_OVERLAP = 150     # overlap between consecutive chunks
TOP_K = 5               # how many chunks to retrieve per question
EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"
GROQ_MODEL = "openai/gpt-oss-120b"

# The Groq key comes ONLY from Streamlit secrets, never hardcoded (step 12).
GROQ_API_KEY = st.secrets.get("GROQ_API_KEY", os.environ.get("GROQ_API_KEY", ""))


@st.cache_resource
def get_embedding_model():
    """Load the Sentence Transformers model once per app run (cached)."""
    from sentence_transformers import SentenceTransformer
    return SentenceTransformer(EMBEDDING_MODEL_NAME)


@st.cache_resource
def get_groq_client():
    from groq import Groq
    if not GROQ_API_KEY:
        return None
    return Groq(api_key=GROQ_API_KEY)


# ----------------------------------------------------------------------------
# 2. DOCUMENT EXTRACTION (one function per file type, each returns a list of
#    (page_number_or_None, text) tuples so we can keep page metadata where it exists)
# ----------------------------------------------------------------------------

def extract_pdf(file_bytes, filename):
    from pypdf import PdfReader
    reader = PdfReader(file_bytes)
    pages = []
    ocr_needed_page_nums = []

    for i, page in enumerate(reader.pages, start=1):
        text = page.extract_text() or ""
        if text.strip():
            pages.append((i, text))
        else:
            # No text layer on this page (common for scans, CAD/drawing
            # exports, or image-only PDFs) — flag it for OCR below.
            ocr_needed_page_nums.append(i)

    if ocr_needed_page_nums:
        ocr_pages = ocr_pdf_pages(file_bytes, ocr_needed_page_nums)
        pages.extend(ocr_pages)

    pages.sort(key=lambda p: p[0])
    return pages


def ocr_pdf_pages(file_bytes, page_numbers):
    """Rasterize specific PDF pages and run OCR on them. Requires the
    tesseract-ocr and poppler system packages to be installed (see README)."""
    try:
        from pdf2image import convert_from_bytes
        import pytesseract
    except ImportError:
        st.warning(
            "Some pages have no text layer and would need OCR (pytesseract/pdf2image), "
            "but those packages aren't installed. Install them to extract text from "
            "scanned or image-only PDF pages."
        )
        return []

    file_bytes.seek(0)
    raw_bytes = file_bytes.read()
    file_bytes.seek(0)

    results = []
    try:
        images = convert_from_bytes(
            raw_bytes,
            dpi=200,
            first_page=min(page_numbers),
            last_page=max(page_numbers),
        )
    except Exception as e:
        st.warning(f"OCR fallback failed to render PDF pages: {e}")
        return []

    start = min(page_numbers)
    for offset, image in enumerate(images):
        page_num = start + offset
        if page_num not in page_numbers:
            continue
        text = pytesseract.image_to_string(image)
        if text.strip():
            results.append((page_num, text))
    return results


def extract_docx(file_bytes, filename):
    import docx
    document = docx.Document(file_bytes)
    text = "\n".join(p.text for p in document.paragraphs if p.text.strip())
    # DOCX has no reliable page numbers, so page is None.
    return [(None, text)]


def extract_txt(file_bytes, filename):
    text = file_bytes.read().decode("utf-8", errors="ignore")
    return [(None, text)]


def extract_md(file_bytes, filename):
    text = file_bytes.read().decode("utf-8", errors="ignore")
    return [(None, text)]


EXTRACTORS = {
    ".pdf": extract_pdf,
    ".docx": extract_docx,
    ".txt": extract_txt,
    ".md": extract_md,
}


def extract_document(file_bytes, filename):
    """Dispatch to the right extractor based on file extension."""
    ext = os.path.splitext(filename)[1].lower()
    if ext not in EXTRACTORS:
        return []
    return EXTRACTORS[ext](file_bytes, filename)


# ----------------------------------------------------------------------------
# 3. TEXT CHUNKING
# ----------------------------------------------------------------------------

def chunk_text(text, chunk_size=CHUNK_SIZE, overlap=CHUNK_OVERLAP):
    """Split text into overlapping chunks (simple character-based sliding window)."""
    text = re.sub(r"\s+", " ", text).strip()
    if not text:
        return []

    chunks = []
    start = 0
    while start < len(text):
        end = start + chunk_size
        chunks.append(text[start:end])
        if end >= len(text):
            break
        start = end - overlap
    return chunks


def build_chunks_for_document(pages, filename):
    """Turn extracted (page, text) pairs into chunk records with metadata."""
    records = []
    for page_num, text in pages:
        for chunk in chunk_text(text):
            records.append({
                "filename": filename,
                "page": page_num,
                "text": chunk,
            })
    return records


# ----------------------------------------------------------------------------
# 4. EMBEDDINGS + FAISS INDEX
# ----------------------------------------------------------------------------

def embed_chunks(chunks):
    """Compute normalized embeddings for a list of chunk dicts."""
    model = get_embedding_model()
    texts = [c["text"] for c in chunks]
    embeddings = model.encode(texts, normalize_embeddings=True, show_progress_bar=False)
    return np.array(embeddings, dtype="float32")


def build_faiss_index(embeddings):
    import faiss
    dim = embeddings.shape[1]
    index = faiss.IndexFlatIP(dim)  # inner product on normalized vectors = cosine similarity
    index.add(embeddings)
    return index


def semantic_search(query, chunks, embeddings, index, top_k=TOP_K):
    model = get_embedding_model()
    query_vec = model.encode([query], normalize_embeddings=True).astype("float32")
    scores, ids = index.search(query_vec, min(top_k, len(chunks)))
    results = []
    for score, idx in zip(scores[0], ids[0]):
        if idx == -1:
            continue
        results.append({**chunks[idx], "semantic_score": float(score)})
    return results


# ----------------------------------------------------------------------------
# 5. KEYWORD SEARCH
# ----------------------------------------------------------------------------

STOPWORDS = {
    "the", "a", "an", "is", "are", "was", "were", "of", "to", "in", "on",
    "for", "and", "or", "what", "how", "does", "do", "did", "with", "this",
    "that", "it", "as", "by", "be", "at", "from",
}


def keyword_score(query, text):
    query_words = {w for w in re.findall(r"\w+", query.lower()) if w not in STOPWORDS}
    if not query_words:
        return 0.0
    text_words = set(re.findall(r"\w+", text.lower()))
    overlap = query_words & text_words
    return len(overlap) / len(query_words)


def keyword_search(query, chunks, top_k=TOP_K):
    scored = [{**c, "keyword_score": keyword_score(query, c["text"])} for c in chunks]
    scored.sort(key=lambda c: c["keyword_score"], reverse=True)
    return scored[:top_k]


# ----------------------------------------------------------------------------
# 6. HYBRID SEARCH (combine semantic + keyword)
# ----------------------------------------------------------------------------

def hybrid_search(query, chunks, embeddings, index, top_k=TOP_K,
                   semantic_weight=0.7, keyword_weight=0.3):
    if not chunks:
        return []

    # Semantic scores for ALL chunks (so we can combine fairly, not just top-k of each)
    model = get_embedding_model()
    query_vec = model.encode([query], normalize_embeddings=True).astype("float32")
    all_scores, all_ids = index.search(query_vec, len(chunks))
    semantic_map = {int(idx): float(score) for idx, score in zip(all_ids[0], all_scores[0]) if idx != -1}

    combined = []
    for i, c in enumerate(chunks):
        sem = semantic_map.get(i, 0.0)
        kw = keyword_score(query, c["text"])
        final = semantic_weight * sem + keyword_weight * kw
        combined.append({**c, "semantic_score": sem, "keyword_score": kw, "final_score": final})

    combined.sort(key=lambda c: c["final_score"], reverse=True)
    return combined[:top_k]


# ----------------------------------------------------------------------------
# 7. GROQ QUESTION ANSWERING
# ----------------------------------------------------------------------------

def ask_groq(question, retrieved_chunks):
    client = get_groq_client()
    if client is None:
        return "⚠️ No GROQ_API_KEY found. Add it to Streamlit secrets to enable answers."

    context = "\n\n".join(
        f"[Source: {c['filename']}"
        f"{', page ' + str(c['page']) if c.get('page') else ''}]\n{c['text']}"
        for c in retrieved_chunks
    )

    system_prompt = (
        "You are a helpful assistant that answers questions using ONLY the "
        "provided document context. If the answer is not contained in the "
        "context, clearly say the information is not available in the "
        "provided documents. Do not use outside knowledge."
    )
    user_prompt = f"Context:\n{context}\n\nQuestion: {question}"

    response = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        temperature=0.2,
    )
    return response.choices[0].message.content


# ----------------------------------------------------------------------------
# 8. GOOGLE DRIVE LOADING
# ----------------------------------------------------------------------------

def extract_drive_file_id(link):
    """Pull the file ID out of any common Google Drive share-link format,
    e.g. .../file/d/<ID>/view, .../open?id=<ID>, or a bare ID."""
    patterns = [
        r"/file/d/([a-zA-Z0-9_-]+)",
        r"[?&]id=([a-zA-Z0-9_-]+)",
        r"^([a-zA-Z0-9_-]{20,})$",  # bare ID, just in case
    ]
    for pattern in patterns:
        match = re.search(pattern, link)
        if match:
            return match.group(1)
    return None


def guess_extension_from_content(path):
    """Detect the real file type by looking at its bytes, not its name.
    Needed because downloading a single Drive file by ID doesn't always
    preserve a recognizable filename/extension."""
    import zipfile

    with open(path, "rb") as f:
        head = f.read(8)

    if head.startswith(b"%PDF"):
        return ".pdf"

    if head[:2] == b"PK":  # zip-based format (docx, xlsx, pptx, or a plain zip)
        try:
            with zipfile.ZipFile(path) as z:
                if "word/document.xml" in z.namelist():
                    return ".docx"
        except zipfile.BadZipFile:
            pass
        return None  # a zip, but not a Word doc we can extract

    # Otherwise, try treating it as plain text (covers .txt and .md alike,
    # since both are extracted identically in this app).
    try:
        with open(path, "r", encoding="utf-8") as f:
            f.read(1024)
        return ".txt"
    except UnicodeDecodeError:
        return None


def load_files_from_drive(drive_link):
    """Download a public Google Drive file or folder link into temp files
    and return a list of (filename, BytesIO) tuples for supported types."""
    import gdown
    from io import BytesIO

    tmp_dir = tempfile.mkdtemp()
    downloaded_paths = []

    try:
        if "/folders/" in drive_link:
            downloaded_paths = gdown.download_folder(url=drive_link, output=tmp_dir, quiet=True)
            downloaded_paths = downloaded_paths or []
        else:
            file_id = extract_drive_file_id(drive_link)
            if not file_id:
                st.error("Could not find a file ID in that Google Drive link.")
                return []
            out_path = gdown.download(id=file_id, output=tmp_dir + os.sep, quiet=True)
            if out_path:
                downloaded_paths = [out_path]
    except Exception as e:
        st.error(f"Could not load from Google Drive: {e}")
        return []

    if not downloaded_paths:
        st.warning("Google Drive returned no files for that link. Double-check it's shared as 'Anyone with the link'.")
        return []

    results = []
    skipped = []
    for path in downloaded_paths:
        filename = os.path.basename(path)
        ext = os.path.splitext(filename)[1].lower()

        if ext not in EXTRACTORS:
            # Filename didn't carry a usable extension — sniff the actual content.
            detected_ext = guess_extension_from_content(path)
            if detected_ext is None:
                skipped.append(filename)
                continue
            ext = detected_ext
            filename = filename + ext  # give it a usable name for downstream extraction

        with open(path, "rb") as f:
            results.append((filename, BytesIO(f.read())))

    if skipped:
        st.warning(f"Skipped unsupported file(s): {', '.join(skipped)}")

    return results


# ----------------------------------------------------------------------------
# 9. STREAMLIT UI
# ----------------------------------------------------------------------------

def init_session_state():
    defaults = {
        "chunks": [],                  # all chunk records (with metadata) across all docs
        "embeddings": None,            # numpy array aligned with chunks
        "faiss_index": None,
        "processed_files": set(),      # content hashes already embedded, to avoid recompute (step 11)
        "processed_filenames": set(),  # display-only: filenames currently loaded
        "chat_history": [],
    }
    for key, value in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = value


def clear_all_documents():
    st.session_state.chunks = []
    st.session_state.embeddings = None
    st.session_state.faiss_index = None
    st.session_state.processed_files = set()
    st.session_state.processed_filenames = set()


def process_new_files(files_with_bytes):
    """Extract, chunk, and embed only files we haven't processed yet.
    We key on a hash of the file's content (not just its filename) so two
    different files that happen to share a name aren't confused for each other."""
    import hashlib

    new_chunks = []
    for filename, file_bytes in files_with_bytes:
        content = file_bytes.read()
        file_bytes.seek(0)
        file_hash = hashlib.sha256(content).hexdigest()

        if file_hash in st.session_state.processed_files:
            continue
        try:
            pages = extract_document(file_bytes, filename)
            chunks = build_chunks_for_document(pages, filename)
        except Exception as e:
            st.sidebar.error(f"Could not process {filename}: {e}")
            continue
        new_chunks.extend(chunks)
        st.session_state.processed_files.add(file_hash)
        st.session_state.processed_filenames.add(filename)

    if not new_chunks:
        return 0

    new_embeddings = embed_chunks(new_chunks)

    st.session_state.chunks.extend(new_chunks)
    if st.session_state.embeddings is None:
        st.session_state.embeddings = new_embeddings
    else:
        st.session_state.embeddings = np.vstack([st.session_state.embeddings, new_embeddings])

    st.session_state.faiss_index = build_faiss_index(st.session_state.embeddings)
    return len(new_chunks)


def main():
    init_session_state()

    st.title("📄 AI Document Assistant")
    st.caption("Upload documents or load them from Google Drive, then ask questions grounded in their content.")

    with st.sidebar:
        st.header("1. Add documents")
        uploaded = st.file_uploader(
            "Upload PDF, DOCX, TXT or MD files",
            type=["pdf", "docx", "txt", "md"],
            accept_multiple_files=True,
        )

        st.divider()
        st.subheader("Or load from Google Drive")
        drive_link = st.text_input("Paste a Google Drive file or folder link")
        load_drive_clicked = st.button("Load from Drive")

        st.divider()
        st.write(f"📚 Documents processed: **{len(st.session_state.processed_filenames)}**")
        st.write(f"🧩 Total chunks: **{len(st.session_state.chunks)}**")
        if st.session_state.processed_filenames:
            with st.expander("Loaded files"):
                for name in sorted(st.session_state.processed_filenames):
                    st.write(f"• {name}")
            if st.button("🗑️ Clear all documents"):
                clear_all_documents()
                st.rerun()

    # --- Handle local uploads ---
    if uploaded:
        files_with_bytes = [(f.name, f) for f in uploaded]
        added = process_new_files(files_with_bytes)
        if added:
            st.sidebar.success(f"Processed {added} new chunk(s).")

    # --- Handle Google Drive ---
    if load_drive_clicked and drive_link:
        with st.spinner("Downloading from Google Drive..."):
            drive_files = load_files_from_drive(drive_link)
        if drive_files:
            added = process_new_files(drive_files)
            st.sidebar.success(f"Loaded {len(drive_files)} file(s), {added} new chunk(s).")
        else:
            st.sidebar.warning("No supported files found at that link.")

    st.divider()
    st.header("2. Ask a question")

    if not st.session_state.chunks:
        st.info("Add at least one document to get started.")
        return

    question = st.text_input("Your question")
    ask_clicked = st.button("Ask")

    if ask_clicked and question:
        with st.spinner("Searching documents and generating answer..."):
            retrieved = hybrid_search(
                question,
                st.session_state.chunks,
                st.session_state.embeddings,
                st.session_state.faiss_index,
                top_k=TOP_K,
            )
            answer = ask_groq(question, retrieved)

        st.subheader("Answer")
        st.write(answer)

        st.subheader("Sources")
        for c in retrieved:
            page_info = f", page {c['page']}" if c.get("page") else ""
            with st.expander(f"📄 {c['filename']}{page_info}  ·  score {c['final_score']:.2f}"):
                st.write(c["text"])


if __name__ == "__main__":
    main()




